name: zx-script
description: Run zx 🐚 script in GitHub Actions.
branding:
  icon: dollar-sign
  color: gray-dark
inputs:
  script:
    default:
runs:
  using: composite
  steps:
    - run: |
        npx zx@3.1.0 << "1d18af1b-6aa5-0661-b706-4fab507ae7b0"
        ${{inputs.script}}
        1d18af1b-6aa5-0661-b706-4fab507ae7b0
      shell: bash
